database:
  enable: false
  host: localhost
  port: 3306
  user: root
  password: root
  database: root
  table: my_database
options:
  fixed:
    integer:
      max: -1
      min: -1
    decimal:
      max: 2
      min: 2